"""alter casereports table

Revision ID: 38b188ca98b2
Revises: cfc040e12ae4
Create Date: 2024-09-03 10:58:43.127071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b188ca98b2'
down_revision = 'cfc040e12ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('case_reports_ibfk_5', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ids', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_reports_ibfk_5', 'user', ['user_ids'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
