"""alter casereport table

Revision ID: 4c5d5e6e5bc7
Revises: 7658a74f0b5f
Create Date: 2024-09-03 09:38:01.203719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c5d5e6e5bc7'
down_revision = '7658a74f0b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=False))
        batch_op.alter_column('files',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key(None, 'appointment', ['appointment_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('files',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
