"""alter casereports table

Revision ID: 53a93f0e3981
Revises: f24d91c1dcba
Create Date: 2024-09-03 15:48:39.843294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53a93f0e3981'
down_revision = 'f24d91c1dcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_pdf', sa.String(length=256), nullable=False),
    sa.Column('report_description', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('case_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_reports',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('appointment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('report_description', mysql.TEXT(), nullable=True),
    sa.Column('files', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name='case_reports_ibfk_1'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='case_reports_ibfk_4'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='case_reports_ibfk_5'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('case_report')
    # ### end Alembic commands ###
