"""alter casereport table

Revision ID: 5ae07216d8eb
Revises: 553be1488e7e
Create Date: 2024-08-29 09:06:19.980198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ae07216d8eb'
down_revision = '553be1488e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_constraint('case_report_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('case_report_ibfk_3', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('case_report_ibfk_3', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('case_report_ibfk_1', 'appointment', ['appointment_id'], ['id'])

    # ### end Alembic commands ###
