"""alter casereports table

Revision ID: 64fd3d0df47f
Revises: 684df3050c88
Create Date: 2024-09-04 09:25:48.624709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fd3d0df47f'
down_revision = '684df3050c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
