"""alter casereports table

Revision ID: 684df3050c88
Revises: 53a93f0e3981
Create Date: 2024-09-04 09:02:24.553567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '684df3050c88'
down_revision = '53a93f0e3981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
