"""alter casereports table

Revision ID: a05ba9ee22c3
Revises: 38b188ca98b2
Create Date: 2024-09-03 15:10:37.424219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a05ba9ee22c3'
down_revision = '38b188ca98b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('appointment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('report_description',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('files',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.alter_column('files',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('report_description',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('appointment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
