"""alter casereport table

Revision ID: a6c0a4fa0084
Revises: a97ba883e711
Create Date: 2024-09-03 10:51:04.442328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c0a4fa0084'
down_revision = 'a97ba883e711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.drop_constraint('case_reports_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_reports_ibfk_2', 'user', ['doctor_id'], ['id'])

    # ### end Alembic commands ###
