"""alter casereport table

Revision ID: bf05709b4d87
Revises: 5ae07216d8eb
Create Date: 2024-08-29 09:11:50.499192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf05709b4d87'
down_revision = '5ae07216d8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'appointment', ['appointment_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
