"""alter casereports table

Revision ID: f24d91c1dcba
Revises: a05ba9ee22c3
Create Date: 2024-09-03 15:15:39.847807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f24d91c1dcba'
down_revision = 'a05ba9ee22c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.alter_column('files',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_reports', schema=None) as batch_op:
        batch_op.alter_column('files',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
