"""alter casereports table

Revision ID: fa5dae0e8ba3
Revises: 64fd3d0df47f
Create Date: 2024-09-04 10:10:52.997446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5dae0e8ba3'
down_revision = '64fd3d0df47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_constraint('case_report_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_report_ibfk_2', 'doctors', ['doctor_id'], ['id'])

    # ### end Alembic commands ###
